{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 4\n +  where 3 = inc(2)", "trace": "def test_answer():\n>       assert inc(2) == 4\nE       assert 3 == 4\nE        +  where 3 = inc(2)\n\nscript\\test_demo1.py:9: AssertionError"}, "start": 1567828616201, "stop": 1567828616201, "uuid": "0cff0932-fc0f-45aa-bc94-698940291474", "historyId": "539409a4d702afc53f91ec1bd02cbdbc", "testCaseId": "c21918c40797cef24aba394eb6470dea", "fullName": "script.test_demo1#test_answer", "labels": [{"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "test_demo1"}, {"name": "host", "value": "DESKTOP-ELQ6K57"}, {"name": "thread", "value": "21176-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.test_demo1"}]}