{"name": "test_answer6", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 4\n +  where 3 = inc(2)", "trace": "def test_answer6():\n>       assert inc(2) == 4\nE       assert 3 == 4\nE        +  where 3 = inc(2)\n\nscript\\test_demo1.py:35: AssertionError"}, "start": 1567828616283, "stop": 1567828616283, "uuid": "dc78ac2d-a33d-4ea0-a7b5-50b416d7c2fd", "historyId": "e8566f73b2484040f4ae4b2f463ea9eb", "testCaseId": "d504f1d37fd047834a7469433060798e", "fullName": "script.test_demo1#test_answer6", "labels": [{"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "test_demo1"}, {"name": "host", "value": "DESKTOP-ELQ6K57"}, {"name": "thread", "value": "21176-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.test_demo1"}]}